language: node_js
node_js:
  - "9"
sudo: true
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  hosts:
    - db-test
services:
  - postgresql
before_script:
  - cp config/scientilla.js.example config/scientilla.js
  - npm i -g mocha@3.X
  - psql -c "CREATE DATABASE scientillatest;" -U postgres
  - psql -c "CREATE USER scientilla WITH PASSWORD 'scientillapassword';"  -U postgres
script:
  - "npm test"
