language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
sudo: false
services:
  - postgresql
before_script:
  - "npm i -g mocha"
  - "psql -c 'CREATE DATABASE scientilla-test;' -U postgres"
  - "psql -c 'CREATE USER scientilla WITH PASSWORD \'scientillapassword\';'  -U postgres"
script:
  - "npm test"