version: '2'

services:
  node:
    build: ./docker/node
    volumes:
      - .:/usr/src/app
    user: "${USERID}"
  npm:
    extends: node
    entrypoint: npm
  bower:
    extends: node
    entrypoint: bower
  mocha:
    extends: node
    entrypoint: mocha
  grunt:
    extends: node
    entrypoint: grunt
  db-test:
    image: postgres:9.6
    environment:
      POSTGRES_DB: scientillatest
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword