version: '2'

services:
  node:
    build: ./docker/node
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
      - "35732:35732"
    command: bash -c "sails lift"
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: