version: '2'

services:
  web:
    build: ./docker/node
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
      - "35732:35732"
      - "5858:5858"
    environment:
      NODE_ENV: development
    command: bash -c "sails debug --expose_debug_as=v8debug > ./logs/sailslog"
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    volumes:
      - scientillapgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword

volumes:
  scientillapgdata: