version: '2'

services:
  node-test:
    build: ./docker/node
    volumes:
      - .:/usr/src/app
    command: bash -c "npm test"
  db-test:
    image: postgres:9.6
    environment:
      POSTGRES_DB: scientillatest
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword