version: '2'

services:
  node:
    build: ./docker/node
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8084:1337"
      - "35732:35732"
      - "5858:5858"
    command: bash -c "sails debug --expose_debug_as=v8debug > ./logs/sailslog"
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword