version: '2'

services:
  node:
    build: ./docker/node
    restart: always
    volumes:
      - ./old:/usr/src/app
    ports:
      - "1337:1337"
      - "35732:35732"
      - "5858:5858"
    environment:
      NODE_ENV: development
    command: bash -c "sails debug --expose_debug_as=v8debug > ./logs/sailslog"

  web:
    build: ./docker/web
    restart: always
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8088:1337"
    command: node app.js

  db:
    image: postgres:10
    restart: always
    volumes:
      - scientillapgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword

volumes:
  scientillapgdata: