version: '2'

services:
  basenode:
    build: ./docker/node
    volumes:
      - .:/usr/src/app
    user: "${USERID}"
  testweb:
    extends: basenode
    command: npm test
    depends_on:
      - testdb
  npm:
    extends: basenode
    entrypoint: npm
  bower:
    extends: basenode
    entrypoint: bower
  mocha:
    extends: basenode
    entrypoint: mocha
  grunt:
    extends: basenode
    entrypoint: grunt
  testdb:
    image: postgres:10
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: scientillatest
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: scientillapassword