version: '2'

services:
  node:
    build: ./docker/node
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
      - "35732:35732"
    command: bash -c "sails lift"
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD:
  web:
    restart: always
    build: ./web
    ports:
      - "1338:8000"
    volumes:
      - ./web:/app/web
      - ./.tmp/:/app/web/project/static
    command: /usr/local/bin/gunicorn --timeout=600 --reload -w 3 -b :8000 project:app
    environment:
      PYTHONUNBUFFERED: 0
      FLASK_APP: project/__init__.py
    working_dir: /app/web
    user: "${USERID}"
    depends_on:
      - node
      - db